from django.conf import settings

COLLECTOR_PANEL_HOST = getattr(settings, 'COLLECTOR_PANEL_HOST')
COLLECTOR_METRICS_INPUT_WORKBOOK = getattr(settings, 'COLLECTOR_METRICS_INPUT_WORKBOOK')
COLLECTOR_METRICS_TOPIC_NAME_PREFIX = getattr(settings, 'COLLECTOR_METRICS_TOPIC_NAME_PREFIX')
COLLECTOR_METRICS_WORKSHEET_NAME = getattr(settings, 'COLLECTOR_METRICS_WORKSHEET_NAME', 'Metrics')
