#!/bin/bash

# A script that downloads shflags if it is not present and executes it.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

set -e
set -o posix

if [ ! -f "$ROOT/scripts/shflags-real" ]; then
  echo -e "\e[1;45mDownloading shflags...\e[0m"
  wget -q -O $ROOT/scripts/shflags-real https://github.com/kward/shflags/raw/master/shflags
fi

set +e
source "$ROOT/scripts/shflags-real"
