#!/bin/bash

# A script that downloads shflags if it is not present and executes it.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

set -e
set -o posix

if [ ! -f "$ROOT/scripts/shflags-real" ]; then
  echo -e "\e[1;45mDownloading shflags...\e[0m"
  wget -q -O $ROOT/scripts/shflags-real https://raw.githubusercontent.com/kward/shflags/5df39c91d3d8804a254bcf2ed3f8432dcc982e1c/lib/shflags
fi

set +e
source "$ROOT/scripts/shflags-real"
